platform :ios, '13.0'

target 'ProtoKanjiAppV.3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProtoKanjiAppV.3

pod 'TableViewReloadAnimation', '~> 0.0'

pod 'Licenses', '~> 2.2'

pod 'ViewControllerPresentationSpy', '~> 6.0'
end

